<?php

/**
 * User: yongli
 * Date: 17/5/9
 * Time: 13:46
 * Email: yong.li@szypwl.com
 * Copyright: 深圳优品未来科技有限公司
 */
namespace App\Controllers;

use \YP\Core\YP_Controller as Controller;
/**
 * Class Auth 权限认证类
 *
 */
class Auth extends Controller
{
    /**
     * 构造函数
     */
    public function initialization()
    {
        parent::initialization(); // TODO: Change the autogenerated stub
    }
}